name: api rust doc

on:
  push:
    branches: [ "main" ]

permissions: {}
jobs:
  deploy:
    permissions:
      contents: write # to push pages branch (peaceiris/actions-gh-pages)

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build api rust doc
        run: cargo doc --no-deps --package chiquito

      - name: Add index.html file to docs root
        run: |
          mkdir -p ./target/doc
          echo '<meta http-equiv="refresh" content="0; url=chiquito">' > ./target/doc/index.html

      - name: Build book
        run: pip install jupyter-book && make book

      - name: Add CNAME file to docs root
        run: |
          mkdir -p ./book/_build/html
          echo 'docs.pecadorplonkish.xyz' > ./book/_build/html/CNAME
          touch ./book/_build/html/.nojekyll

      - name: Deploy book
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/_build/html
          destination_dir: ./docs

#      - name: Deploy Api docs
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: ./target/doc
#          destination_dir: ./docs/apidocs